import React, { useState } from 'react';
import { Copy, Check, RefreshCw, Code } from 'lucide-react';

export default function JsonOutputView({ milestones, onReset }) {
    const [copied, setCopied] = useState(false);
    // milestones is now the full string (Prompt A + JSON)
    const displayContent = typeof milestones === 'string' ? milestones : JSON.stringify(milestones, null, 2);

    const handleCopy = () => {
        navigator.clipboard.writeText(displayContent);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className="min-h-screen p-6 md:p-12 flex flex-col items-center max-w-5xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="w-full flex items-center justify-between border-b border-lavender-light pb-6">
                <div className="flex items-center gap-3">
                    <div className="p-3 bg-lavender-light rounded-2xl text-lavender-dark">
                        <Code size={24} />
                    </div>
                    <div>
                        <h2 className="text-2xl font-bold text-chart_text">Claude Prompt Template</h2>
                        <p className="text-gray-400 text-sm">Agent 5 output wrapped in Prompt A</p>
                    </div>
                </div>
                <div className="flex gap-4">
                    <button
                        onClick={onReset}
                        className="flex items-center gap-2 px-6 py-3 glass-panel rounded-xl font-bold text-sm text-gray-500 hover:text-lavender hover:bg-lavender-light transition-all"
                    >
                        <RefreshCw size={18} />
                        New Search
                    </button>
                    <button
                        onClick={handleCopy}
                        className="flex items-center gap-2 px-6 py-3 bg-lavender text-white rounded-xl font-bold text-sm hover:bg-lavender-dark transition-all shadow-lg shadow-lavender/20"
                    >
                        {copied ? <Check size={18} /> : <Copy size={18} />}
                        {copied ? 'Copied!' : 'Copy Prompt'}
                    </button>
                </div>
            </div>

            <div className="w-full relative group">
                <div className="absolute -inset-1 bg-gradient-to-r from-lavender/20 to-blue-400/20 blur opacity-25 group-hover:opacity-50 transition duration-1000 group-hover:duration-200" />
                <pre className="relative w-full bg-white border border-lavender-light rounded-3xl p-8 overflow-x-auto text-sm font-mono text-gray-700 custom-scrollbar shadow-2xl">
                    <code>{displayContent}</code>
                </pre>
            </div>
            
            <p className="text-gray-400 text-xs italic">
                * This JSON contains the canvas specifications, state trackers, and animation steps generated by the multi-agent system.
            </p>
        </div>
    );
}
